#!/bin/bash

# Colors
# Colors
ESC_SEQ="\x1b["
COL_RESET=$ESC_SEQ"39;49;00m"
COL_RED=$ESC_SEQ"31;01m"
COL_GREEN=$ESC_SEQ"32;01m"
COL_YELLOW=$ESC_SEQ"33;01m"

# Variables
# Input directory is $PWD
INPUT_DIR="."


FOUND_ERROR="FALSE"


CWD_BLACKLIST=.word-lintrc

function checkBlackListCWD () {
  blacklist_file=$1
  filepath=$2

  if [ -f "$blacklist_file" ]; then
    while IFS= read -r CHECK
    do
      if [ "$CHECK" != "" ]; then

        ERRORS=$(grep -wnr --color --exclude=".word-lintrc" --exclude="word_choice.rst" "${CHECK}" "$filepath" >&1)

        if [ "$ERRORS" != "" ]; then

          if [ "$FOUND_ERROR" = "FALSE" ]; then
            FOUND_ERROR="TRUE"
          fi

          echo -en "$COL_YELLOW $CHECK $COL_RESET\n"
          echo -e "$ERRORS"
        fi
      fi
    done < "$blacklist_file"
  fi
}

# Check if we have a config file in $PWD
FILE=$PWD/.plone-lintrc
if [ -f $FILE ]; then
	echo -en "$COL_GREEN Running Checks ... $COL_RESET\n"
    checkBlackListCWD $CWD_BLACKLIST "$INPUT_DIR"
else
    echo -en "$COL_RED Can't find a config $COL_RESET\n"
    exit 1
fi

if [ "$FOUND_ERROR" = "TRUE" ]; then
    echo
    echo -en "$COL_RED Found certain words, please resolve.$COL_RESET\n"
    exit 1
fi
